USE PLUS_Reports
TRUNCATE TABLE PLUS_Reports..AgentGroup
TRUNCATE TABLE PLUS_Reports..AgentHardware
TRUNCATE TABLE PLUS_Reports..AgentOSAttributes
TRUNCATE TABLE PLUS_Reports..Agents
TRUNCATE TABLE PLUS_Reports..AgentServices
TRUNCATE TABLE PLUS_Reports..AgentSoftware
TRUNCATE TABLE PLUS_Reports..AgentToIP
TRUNCATE TABLE PLUS_Reports..AgentToMAC
TRUNCATE TABLE PLUS_Reports..DeploymentDetail
TRUNCATE TABLE PLUS_Reports..Deployments
TRUNCATE TABLE PLUS_Reports..ERSLogs
TRUNCATE TABLE PLUS_Reports..ERSProcessID
TRUNCATE TABLE PLUS_Reports..Groups
TRUNCATE TABLE PLUS_Reports..License
TRUNCATE TABLE PLUS_Reports..MandatoryPackagesToGroups
TRUNCATE TABLE PLUS_Reports..MandatoryVulnerabilitiesToGroups
TRUNCATE TABLE PLUS_Reports..OperatingSystems
TRUNCATE TABLE PLUS_Reports..Packages
TRUNCATE TABLE PLUS_Reports..PLUSAccountInfo
TRUNCATE TABLE PLUS_Reports..SignatureAnalysis
TRUNCATE TABLE PLUS_Reports..SignaturesToOperatingSystems
TRUNCATE TABLE PLUS_Reports..SnapshotERSStatus
TRUNCATE TABLE PLUS_Reports..SnapshotGenerationStatus
TRUNCATE TABLE PLUS_Reports..Snapshots
TRUNCATE TABLE PLUS_Reports..SnapshotUploadStatus
TRUNCATE TABLE PLUS_Reports..UpdateServerUser
TRUNCATE TABLE PLUS_Reports..UpdateServerUserRole
TRUNCATE TABLE PLUS_Reports..UpdateServerUserRoleDevice
TRUNCATE TABLE PLUS_Reports..UpdateServerUserRoleGroup
TRUNCATE TABLE PLUS_Reports..Vulnerabilities
TRUNCATE TABLE PLUS_Reports..VulnerabilitiesToVulnerabilityCodes
TRUNCATE TABLE PLUS_Reports..VulnerabilityCodes
TRUNCATE TABLE PLUS_Reports..VulnerabilitySignatures
